### PR TITLE
Initial Release

### PR DESCRIPTION
**Pull request by hanlonm**

### CODE REVIEW

**Comment by hanlonm** [comment]
> @hanlonm please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

**Review by EricVoll — APPROVED** [review]

**Comment by EricVoll** [comment]
Thanks @hanlonm, you can go ahead an merge the PR :)

**Review by EricVoll — CHANGES_REQUESTED** [review]
Actually, please check the gitignore again. I can see that the PR contains the TextMeshPro package for example, which shouldn't be necessary.

**Comment by hanlonm** [comment]
@EricVoll I made a small modification to the Unity .gitignore. However, adding the TextMeshPro to the .gitignore removes some assets required for the application to work put of the box. See attached image:
image

**Comment by EricVoll** [comment]
Right, I expected TextMeshPro also to be added to the package manifest, but apparently that's not happening and people would have to add the package manually via the PackageManager. Apparently it's the way to go to push this huge folder into the repo, which is weird, but well. 

However, we can remove the niryo-one URDF folder. That's not used in the demo.

I'm just trying to find a few places where we can eliminate some of those 1600 files...

**Comment by hanlonm** [comment]
I removed the unused URDF and other files I could find. Down to 1200 files 😅

**Review by EricVoll — APPROVED** [review]

**Comment by EricVoll** [comment]
ok, thanks!

**Comment by EricVoll** [comment]
If you want you can click the merge button now, otherwise I'll do that tomorrow or so :)

**Comment by hanlonm** [comment]
Thanks for the feedback!

**Pull request merged**
